import Header from "@/components/common/header/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchLogo() : Promise<string | null> {
  try {
    const apiUrl = process.env.API_ENDPOINT ||
     process.env.NEXT_PUBLIC_API_URL ||
      "http://localhost:8000";
    const response = await fetch(`${apiUrl}/api/website-icons/key/main_logo`, {
      next: {revalidate: 3600},
      signal: AbortSignal.timeout(5000)
    });
    if (response.ok) {
      const data = await response.json();
      if (data.success && data.data?.imageUrl) {
        return data.data.imageUrl;
      }
    }
  } catch (error) {
    console.error("Error fetching logo (using default):", error);
  }
  return null;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const logoUrl = await fetchLogo();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Header
      logoUrl={logoUrl}
       />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
